### PR TITLE
Update reports

### PR DESCRIPTION
**Pull request by scilganon**
#46 am i on the right way to update reports to the new schema?

### CODE REVIEW

**Comment by scilganon** [comment]
@slodki should be done such changes? is anybody already did it?

**Comment by slodki** [comment]
Please use new `check_gm` script from #51 - correct DB schema will be downloaded on-the-fly

**Comment by slodki** [comment]
This report is very buggy - it ignores split transactions, sums up different currencies etc. It's quite easy to update SQL to renamed table names, but it's hard to support latest MMEX features.

**Comment by slodki** [comment]
Please check #53 for common problems with MMEX errors. UML diagram in [database README](https://github.com/moneymanagerex/database/blob/master/README.md) can help to create right SQL queries like in [#1662](https://github.com/moneymanagerex/moneymanagerex/issues/1662#issuecomment-393546759)

**Comment by slodki** [comment]
GRM flow: SQLite &rarr; SQL &rarr; Lua &rarr; template &rarr; JS &rarr; HTML
GRM reports can use user-selected parameters and filters to modify output.
It's hard to verity if values presented in HTML are correct using prepared sample transactions in db IMHO.

**Comment by vomikan** [comment]
I've made a lot of changes with this repo.
- Report grouping
- Only DB v7 support
- Readme.md for all groups

mmex v 1.4.0 stuck

**Pull request closed without merging**
