### PR TITLE
Reports updated mostly for currency conversion, split where appropriate and ignore Duplicate Tx

### PR DESCRIPTION
**Pull request by siowena**
Using some of the points in #53 as a guide (and also updated as I needed them to work) 

- AccountForecast
  - Exclude **D**uplicate transactions
  - Formatting of values - Support Accounts with Multiple currencies
  - Formatting currency figures - Using values from currency table to format values correctly using currency values (prefix; suffix; decimal; group separator) on the reports using javascript. If values don't exist, then use the base currency values
  - General updates - Changed so account name come from SQL and no editing of htt is needed
  - Use account's currency & display on page - Display the currency the report is in (using the account's currency setting) and format the amounts as numbers correctly with the decimal & 1000's grouping characters.

- AccountSummary
  - Exclude **D**uplicate transactions
  - Formatting of values - Support Accounts with Multiple currencies
  - Currency conversion - Pickup the latest currency conversion from the CURRENCYHISTORY_V1 table. If there are no value, then use CURRENCYFORMATS_V1.BASECONVRATE
  - Formatting currency figures - Using values from currency table to format values correctly using currency values (prefix; suffix; decimal; group separator) on the reports using javascript. If values don't exist, then use the base currency values

- AccountTrend4
  - Exclude **D**uplicate transactions
  - Support for accounts in non-base currency - Display values in the account's currency formats
  - Formatting currency figures - Using values from currency table to format values correctly using currency values (prefix; suffix; decimal; group separator) on the reports using javascript. If values don't exist, then use the base currency values
  - General updates - Changed so account name come from SQL and no editing of htt is needed.

- AttachmentList
  - HTML5 checks
  - Exclude **D**uplicate & **V**oid transactions.

- BlankNotes
  - Currency conversion - Pickup the latest currency conversion from the CURRENCYHISTORY_V1 table. If there are no value, then use CURRENCYFORMATS_V1.BASECONVRATE.
  - Formatting currency figures - Using values from currency table to format values correctly using currency values (prefix; suffix; decimal; group separator) on the reports using javascript. If values don't exist, then use the base currency values
  - template.htt file changes to UTF-8 encoding

- BudgetMonitoringCurrenctMonth
  - Exclude **D**uplicate transactions

- BudgetMonitoringLastMonth
  - Exclude **D**uplicate transactions

- CategoriesStatLast12Months
  - Currency conversion - Pickup the latest currency conversion from the CURRENCYHISTORY_V1 table. If there are no value, then use CURRENCYFORMATS_V1.BASECONVRATE.

- CategoryForecast
  - Exclude **D**uplicate transactions
  - Convert to BaseCurrency and use Split Transactions
  - Currency conversion - Pickup the latest currency conversion from the CURRENCYHISTORY_V1 table. If there are no value, then use CURRENCYFORMATS_V1.BASECONVRATE.
  - CheckingAccount also now use SplitTransactions (check CATEGID = -1)
  - Billdeposits Account also now use BudgetSplitTransactions (check CATEGID = -1)

- CategoryTrend
  - Exclude **D**uplicate transactions
  - Currency conversion - Pickup the latest currency conversion from the CURRENCYHISTORY_V1 table. If there are no value, then use CURRENCYFORMATS_V1.BASECONVRATE.
  - Changed the SUBCATEGORY_V1 to left join as not all Categories have a subcategory (Other Expenses) and Transactions can be put at Category level by user.

- CreditReport
  - report now picks up Credit Limit from the account record.
  - Support Accounts in difference currencies
  - Formatting currency figures - Using values from currency table to format values correctly using currency values (prefix; suffix; decimal; group separator) on the reports using javascript. If values don't exist, then use the base currency values
  - Currency conversion - Pickup the latest currency conversion from the CURRENCYHISTORY_V1 table. If there are no value, then use CURRENCYFORMATS_V1.BASECONVRATE.
  - HTML5 checks
  - Exclude **D**uplicate transactions

- CreditReport2
  - HTML5 checks
  - Exclude **D**uplicate transactions
  - Currency conversion - Pickup the latest currency conversion from the CURRENCYHISTORY_V1 table. If there are no value, then use CURRENCYFORMATS_V1.BASECONVRATE.
  - correct transactions records to use TOTRANSAMOUNT as this is needed for transfer between accounts of difference currencies

- CurrencySummary
  - Currency format and rates
  - Currency conversion - Pickup the latest currency conversion from the CURRENCYHISTORY_V1 table. If there are no value, then use CURRENCYFORMATS_V1.BASECONVRATE.
  - Displayed prefix & suffix symbol(s) of the currency
  - Displayed example formatting for each currency.

- DepositVsExpensesAndLoadRepaymentsByMonth
  - Exclude **D**uplicate transactions

- ExpenditureHistory
  - Support for multiple currencies
  - Currency conversion - Pickup the latest currency conversion from the CURRENCYHISTORY_V1 table. If there are no value, then use CURRENCYFORMATS_V1.BASECONVRATE.
  - CheckingAccount also now use SplitTransactions (check CATEGID = -1)
  - Correction to Total column, now include current month's expenses.

- IncomeVsExpenseTransactionsByYear
  - New Report Income vs. Expense Transactions By Year
  - Made report configurable for Calendar or Financial Year - The report has two parameters in SQL, one to set to Calendar or Financial Year and the 2nd to set the years the report should show collated values for

- PayeeTrend
  - Exclude **D**uplicate transactions

- SavingsProgress
  - Exclude **D**uplicate transactions

- usercoloredtransactions
  - Currency conversion - Pickup the latest currency conversion from the CURRENCYHISTORY_V1 table. If there are no value, then use CURRENCYFORMATS_V1.BASECONVRATE.
  - Formatting currency figures - Using values from currency table to format values correctly using currency values (prefix; suffix; decimal; group separator) on the reports using javascript. If values don't exist, then use the base currency values
  
- YearlyExpenseAndRevenue
  - Switch to ChartNew.js from Chart.js.
  - Exclude Void & Duplicates & Transfers.
  - Currency conversion - Pickup the latest currency conversion from the CURRENCYHISTORY_V1 table. If there are no value, then use CURRENCYFORMATS_V1.BASECONVRATE.
  - Formatting currency figures - Using values from currency table to format values correctly using currency values (prefix; suffix; decimal; group separator) on the reports using javascript. If values don't exist, then use the base currency values

### CODE REVIEW

**Comment by slodki** [comment]
Please remove  `check_gm.py`, `pack_gm.py` and `tables_v1.sql` files from your PR

**Comment by slodki** [comment]
@siowena please re-add ` .DS_Store` to `.gitignore` and remove it from PR.
Then all technical problems will be fixed. I've no time to verify your reports' changes.

**Comment by siowena** [comment]
Will do on the .github file.

However, the SQL check_gm.py now fails travis-ci after the DB V11 checks due to tablename changes - is that OK, or am I missing something?

**Comment by slodki** [comment]
We have reports for the old db schema only - so it's ok SQL queries are not working with MMEX 1.4.x db. We need something like #52 to support users with different MMEX versions.

**Pull request merged**
